#cloud-config
users:
  - name: naurus
    groups: wheel
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh_authorized_keys:
      - ssh-rsa
packages:
  - screen
  - tmux
  - vim
  - wget
runcmd:
  - [ sed, -i, -e, 's/#PermitRootLogin yes/PermitRootLogin no/g', /etc/ssh/sshd_config ]
  - [ sed, -i, -e, 's/#Port 22/#Port 2222/g', etc/ssh/sshd_config ]
  - systemctl restart sshd
  - [ curl, 'https://raw.githubusercontent.com/khaledalhashem/linux/master/configs.sh', -o, /root/configs.sh ]
  - [ bash, -x, /root/configs.sh ]
  - [ bash, -x, /root/firewall.sh ]
write_files:
  - path: /home/knaved/runme.sh
    content: |
      curl -o .bashrc https://raw.githubusercontent.com/khaledalhashem/linux/master/bashrc
      curl -o .tmux.conf https://raw.githubusercontent.com/khaledalhashem/linux/master/tmux.conf
    owner: knaved:knaved
    permissions: '0600'
manage-resolv-conf: true
resolv_conf:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

  - [curl, 'https://raw.githubusercontent.com/khaledalhashem/linux/master/bashrc', -o, /root/.bashrc]
  - [curl, 'https://raw.githubusercontent.com/khaledalhashem/linux/master/tmux.conf', -o, /root/.tmux.conf]
  - [curl, 'https://raw.githubusercontent.com/khaledalhashem/linux/master/firewll.sh', -o, /root/firewall.sh]
  - [ sh, -x, /root/firewall.sh ]
